version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: password123
    ports:
       # AMQP protocol port
       - '5672:5672'
       # HTTP management UI
       - '15672:15672'
    networks:
      - backend
    
  web-server:
    build: ./web-server
    image: web-server-img
    container_name: web-server
    depends_on:
    - rabbitmq
    - mongodb
    environment:
      APP_PORT: 5000
    volumes:
      # Host directory : Container directory
      - ./web-server:/web-server
    ports:
      - "5000:5000"
    networks:
      - backend
    command: python3 main.py

  sfm-worker:
      build: ./colmap
      image: sfm-worker-img
      container_name: sfm-worker
      depends_on:
        - rabbitmq
      volumes:
        - ./colmap:/sfm-worker
      ports: 
        - 5100:5100
      networks:
        - backend 
      command: python3.10 main.py

networks:
  backend:
    name: backend-network
    driver: bridge

volumes:
  mongodb_data_container: