# -----------------------------------------------------------------------
# Single-stage build
FROM nvidia/cuda:12.3.2-devel-ubuntu22.04

# Set the CUDA_HOME environment variable
# ENV CUDA_HOME=/usr/local/cuda:/home/simondk/miniconda3/bin/nvcc

# Install necessary build dependencies and conda
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Download and install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p /opt/conda \
    && rm miniconda.sh

# Set the CONDA_PREFIX environment variable
ENV CONDA_PREFIX=/opt/conda

# Set the CUDA_HOME environment variable based on CONDA_PREFIX
ENV CUDA_HOME=$CONDA_PREFIX

# Copy source code, including the submodules
COPY . /gaussian_splatting_reduced
WORKDIR /gaussian_splatting_reduced

# Set up the conda environment
COPY environment.yml .
RUN /opt/conda/bin/conda env create -f environment_nopip.yml

# Activate the conda environment
ENV PATH=/opt/conda/envs/gaussian_splatting_reduced/bin:$PATH
RUN echo "Conda environment activated"

# Build and install the CUDA extensions / SubModules
RUN cd submodules/diff-gaussian-rasterization && \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cd ../../ && \
    cd submodules/simple-knn && \
    python setup.py bdist_wheel && \
    pip install dist/*.whl
# Set up the runtime environment
ENV PYTHONPATH=/gaussian_splatting_reduced

# Echo success
RUN echo "Build successful"