import subprocess
import os
import sys

from debug import debug_log
from status import Status

# Usage: python colmap_runner.py --flags
# Flags: --output_folder "path"   ==> Directory to where colmap will put its output.
#                                  > Defaults to the folder where this script is
#
#       --name "name"            ==> Name of the folder to be created to store the data for this instance
#                                  > of colmap.
#                                  > Defaults to "colmap_output"
#
#       --colmap_exe_path "path" ==> Path to the colmap executeable.
#                                  > Defaults to looking for COLMAP.bat in a folder called COLMAP in the
#                                  > folder this script is in
#
#       --image_path "path"      ==> Path to the folder containing the images for COLMAP's input
#                                  > Defailts to looking for a folder called "Images" in the folder
#                                  > this script is in


# run_colmap function:
#
# creates a new folder called instance_name in output_path and fills it with the colmap data
#    generated by the exe at colmap_path with data from images_path
#
# returns a Status code - refer to status.py for more information

def run_colmap(instance_name, output_path, colmap_path, images_path) -> Status:
    # Create a new folder to store our data
    # Add a / to the path if there isn't one
    if not output_path.endswith(("\\", "/")) and not instance_name.startswith(("\\", "/")):
        output_path = output_path + "/"
    instance_path = output_path + instance_name

    try:
        os.mkdir(instance_path)
    except FileNotFoundError:
        return Status.FILE_NOT_FOUND
    except FileExistsError:
        return Status.FILE_EXISTS
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    # Creating a new database for colmap
    try:
        database_path = instance_path + "/database.db"
        subprocess.call([colmap_path, "database_creator",
                        "--database_path", database_path])
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    # Feature extracting
    try:
        subprocess.call([colmap_path, "feature_extractor",
                        "--database_path", database_path, "--image_path", images_path])
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    # Feature matching
    try:
        subprocess.call([colmap_path, "exhaustive_matcher",
                        "--database_path", database_path])
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    # Generating model
    try:
        subprocess.call([colmap_path, "mapper", "--database_path", database_path,
                        "--image_path", images_path, "--output_path", instance_path])
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    # Getting model as text
    try:
        subprocess.call([colmap_path, "model_converter", "--input_path", instance_path +
                        r"\0", "--output_path", instance_path, "--output_type", "TXT"])
    except Exception as e:
        debug_log(e)
        return Status.UNKNOWN

    return Status.SUCCESS


if __name__ == '__main__':
    # Default flags
    instance_name = "colmap_output"
    output_path = "./"
    colmap_path = r".\COLMAP\COLMAP.bat"
    images_path = r".\Images"

    # Parse flags
    # Flag format up top
    for i in range(len(sys.argv)):
        if i == 0:
            continue
        if sys.argv[i].startswith("--"):
            match sys.argv[i]:
                case "--output_folder":
                    output_path = sys.argv[i+1]
                case "--name":
                    instance_name = sys.argv[i+1]
                case "--colmap_exe_path":
                    colmap_path = sys.argv[i+1]
                case "--image_path":
                    images_path = sys.argv[i+1]
                case _:
                    print("ERROR: Unrecognized flag", sys.argv[i])
                    quit()

    # Run COLMAP :)
    status = run_colmap(instance_name, output_path, colmap_path, images_path)

    if status == Status.SUCCESS:
        print("COLMAP ran successfully.")
    elif status == Status.UNKNOWN:
        print("ERROR: There was an unknown error running COLMAP")
    elif status == Status.FILE_NOT_FOUND:
        print(f"ERROR: COLMAP - file {output_path} could not be found.")
    elif status == Status.FILE_EXISTS:
        print(
            f"ERROR: COLMAP - file {output_path}/{instance_name} already exists.")
