import subprocess
import os
import sys
import logging
from pathlib import Path

#Usage: python colmap_runner.py --flags
#Flags: --colmap_exe_path "path" ==> Path to the colmap executeable.
#                                  > Defaults to looking for COLMAP.bat in a folder called COLMAP in the 
#                                  > folder this script is in
#
#       --image_path "path"      ==> Path to the folder containing the images for COLMAP's input
#                                  > Defailts to looking for a folder called "Images" in the folder 
#                                  > this script is in
#
#       --name "name"            ==> Name of the folder to be created to store the data for this instance
#                                  > of colmap.
#                                  > Defaults to "colmap_output"
#
#       --output_folder "path"   ==> Directory to where colmap will put its output.
#                                  > Defaults to the folder where this script is



#run_colmap function:
#
#creates a new folder called instance_name in output_path and fills it with the colmap data
#    generated by the exe at colmap_path with data from images_path
#
#returns a status code -

#    0 = Success
#    1 = Unspecified error
#    2 = FileExistsError; happens when you try to create data in an already existing folder
#    3 = FileNotFoundError; happens when you try to use an output folder that does not exist

def run_colmap(colmap_path, images_path, output_path):
    ### Create a new folder to store our data
    # TODO: determine GPU use on start
    use_gpu = "false"
    Path(f"{output_path}").mkdir(parents=True, exist_ok=True)

    # sfm-worker logger
    logger = logging.getLogger('sfm-worker')


    logger.info("run_colmap()-colmap_path: " + colmap_path)
    logger.info("run_colmap()-images_path: " + images_path)
    logger.info("run_colmap()-output_path: " + colmap_path)

    #Creating a new database for colmap
    try:
        database_path = output_path + "/database.db"
        subprocess.call([colmap_path, "database_creator", "--database_path", database_path])
        logger.info("Created DB")
    except:
        logger.error("DB Creation Failed")
        return 1

    #Feature extracting
    try:
        # --SiftExtraction.use_gpu=false for docker
        # TODO: make gpu use dynamic
        subprocess.call([colmap_path, "feature_extractor","--ImageReader.camera_model","PINHOLE",f"--SiftExtraction.use_gpu={use_gpu}","--ImageReader.single_camera=1", "--database_path", database_path, "--image_path", images_path])
        logger.info("Features Extracted")
    except:
        logger.error("Features unable to be extracted")
        return 1

    #Feature matching
    try:
        subprocess.call([colmap_path, "exhaustive_matcher",f"--SiftMatching.use_gpu={use_gpu}", "--database_path", database_path])
        logger.info("Feature Matched")
    except:
        logger.error("Features unable to be matched")
        return 1

    #Generating model
    try:
        subprocess.call([colmap_path, "mapper", "--database_path", database_path, "--image_path", images_path, "--output_path", output_path])
        logger.info("Model generated")
    except:
        logger.error("Model unable to be generated")
        return 1

    #Getting model as text
    try:
        # TODO: no longer works on windows fix file paths or run in docker
        subprocess.call([colmap_path, "model_converter", "--input_path", output_path + r"/0", "--output_path", output_path, "--output_type", "TXT"])
        logger.info("Model as text successful")
    except:
        logger.error("Model as text unsuccessful")
        return 1

    logger.info("run_colmap successfully executed")
    return 0


if __name__ == '__main__':
    #Default flags
    instance_name = "colmap_output"
    output_path = "./"
    colmap_path = r".\COLMAP\COLMAP.bat"
    images_path = r".\Images"

    logger = logging.getLogger('sfm-worker')

    #Parse flags
    #Flag format up top
    for i in range (len(sys.argv)):
        if i == 0:
            continue
        if sys.argv[i].startswith("--"):
            match sys.argv[i]:
                case "--output_folder":
                    output_path = sys.argv[i+1]
                case "--name":
                    instance_name = sys.argv[i+1]
                case "--colmap_exe_path":
                    colmap_path = sys.argv[i+1]
                case "--image_path":
                    images_path = sys.argv[i+1]
                case _:
                    logger.error("ERROR: Unrecognized flag {}".format(sys.argv[i]))
                    quit()

    #Run COLMAP :)
    status = run_colmap(instance_name, output_path, colmap_path, images_path)
    if status == 0:
        logger.info("COLMAP ran successfully.")
    elif status == 1:
        logger.error("ERROR: There was an unknown error running COLMAP")
    elif status == 2:
        logger.error("ERROR: COLMAP - file {}/{} already exists.".format(output_path,instance_name))
    elif status == 3:
        logger.error("ERROR: COLMAP - file {} could not be found.".format(output_path))
    elif status == 4:
        logger.error("ERROR: COLMAP - Video was too blurry for computation.")
